# Generated by Django 2.2.6 on 2020-12-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201216_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='У меня ещё нет статуса, но когда-то он должен появиться', max_length=200, verbose_name='Статус'),
        ),
    ]
