# Generated by Django 2.2.6 on 2020-12-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201216_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='', max_length=200, verbose_name='Статус'),
        ),
    ]
