# Generated by Django 2.2.6 on 2020-12-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201216_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, max_length=200, verbose_name='Статус'),
        ),
    ]
